model: "FasterSpeech Mels Predictor (LJSpeech)"
sample_rate: &sample_rate 22050
n_mels: &n_mels 80
pad16: &pad16 false
labels: [
  # Space
    ' ',
  # string.ascii_lowercase
    'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm',
    'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',
  # Punctuation
    ',', '.', '!', '?', ';', ':', '-', '/',
    '"', "'", '(', ')', '[', ']', '{', '}',
]

FasterSpeechDataLayer_train:
    sample_rate: *sample_rate
    normalize_transcripts: true
    trim_silence: false
    drop_last: true
    shuffle: true
    sampler_type: 'default'  # SSS produces same 0.65 mask usage on average.

FasterSpeechDataLayer_eval:
    sample_rate: *sample_rate
    normalize_transcripts: true
    trim_silence: false
    drop_last: false  # Mind the BN.
    shuffle: false
    sampler_type: 'all'  # Eval is single batch of 64.

AudioToMelSpectrogramPreprocessor:  # Full good-TTS config.
    sample_rate: *sample_rate
    window_size: null  # Because "n_window_size" below is set.
    window_stride: null  # Because "n_window_size" below is set.
    n_window_size: 1024
    n_window_stride: 256
    window: 'hann'
    normalize: null  # Seems like it's bad for TTS.
    n_fft: 1024
    preemph: null
    features: *n_mels  # 80 works good for TTS.
    lowfreq: 0
    highfreq: 8000
    log: true
    log_zero_guard_type: 'clamp'  # 'clamp' just seems more reasonable.
    log_zero_guard_value: 1e-05
    dither: 0.0
    pad_to: 1  # 16 would be better choice, but we pad manually in encoder/loss classes.
    frame_splicing: 1
    stft_conv: true
    pad_value: -11.52
    mag_power: 1.0  # People use 1.0 for TTS for some reason.

LenSampler:
    max_len: 1100  # Max LJSpeech dur is 10.10sec, so it's never happens.

FasterSpeech:
    d_char: 512
    pad16: *pad16

# QuartzNet15x5 without 2x First Stride and Jasper's kernel sizes
dropout: &dropout 0.0  # Having dropout more than 0.1 doesn't make sense for LJSpeech.
separable: &separable true  # Non-separable one greatly increase number of weights.
JasperEncoder:
    activation: "relu"
    conv_mask: true

    # (Number of Layers) x (Number of Filters) x (Kernel Size)
    jasper:
        # Group 1: 1 x 512 x 3 (First Layer)
        -   filters: 512
            repeat: 3  # Was 1 in Original QuartzNet15x5.
            kernel: [3]  # 5 and 7 works a bit worse.
            stride: [1]  # Was 2 in Original QuartzNet15x5.
            dilation: [1]
            dropout: 0.0
            residual: true  # Non-residual works a bit worse.
            separable: *separable

        # Group 2: 3 x 512 x (5,7,9)
        -   filters: 512
            repeat: 5
            kernel: [5]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: *separable

        -   filters: 512
            repeat: 5
            kernel: [7]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: *separable

        -   filters: 512
            repeat: 5
            kernel: [9]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: *separable

        # Group 3: 3 x 512 x (15=>19)
        -   filters: 512
            repeat: 5
            kernel: [15]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: *separable

        -   filters: 512
            repeat: 5
            kernel: [17]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: *separable

        -   filters: 512
            repeat: 5
            kernel: [19]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: *separable

        # Group 4: 3 x 512 x (21=>25)
        -   filters: 512
            repeat: 5
            kernel: [21]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: *separable

        -   filters: 512
            repeat: 5
            kernel: [23]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: *separable

        -   filters: 512
            repeat: 5
            kernel: [25]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: *separable

        # Group 5: 1 x 512 x 29 (Last Layer)
        -   filters: 512
            repeat: 1
            kernel: [29]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: *separable

        # Last 1x1 Conv
        -   filters: 1024
            repeat: 1
            kernel: [1]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true  # Non-residual works a bit worse.

FasterSpeechMelLoss:
    reduction: 'all'
    pad16: *pad16
