model: "FasterSpeech"
sample_rate: &sample_rate 24000
labels: [
  # Space
    ' ',
  # string.ascii_lowercase
    'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm',
    'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',
  # Punctuation
    "'",
]

FasterSpeechDataLayer_train:
    sample_rate: *sample_rate
    max_duration: 20.0  # ~= -30h. This wasn't applied for inferred durations.
    normalize_transcripts: true
    trim_silence: true
    drop_last: true
    shuffle: true

FasterSpeechDataLayer_eval:
    sample_rate: *sample_rate
    normalize_transcripts: true
    trim_silence: true
    drop_last: false
    shuffle: false

JasperEncoder:
    activation: "relu"
    conv_mask: true

    # (Number of Layers) x (Number of Filters) x (Kernel Size)
    jasper:
        # 3 x 256 x 5
        -   filters: 256
            repeat: 1
            kernel: [5]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: false
            separable: true

        -   filters: 256
            repeat: 5
            kernel: [5]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 256
            repeat: 5
            kernel: [5]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        # 3 x 256 x 7
        -   filters: 256
            repeat: 5
            kernel: [7]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 256
            repeat: 5
            kernel: [7]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 256
            repeat: 5
            kernel: [7]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        # 3 x 512 x 10
        -   filters: 512
            repeat: 5
            kernel: [10]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 512
            repeat: 5
            kernel: [10]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 512
            repeat: 5
            kernel: [10]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        # 3 x 512 x 15
        -   filters: 512
            repeat: 5
            kernel: [15]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 512
            repeat: 5
            kernel: [15]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 512
            repeat: 5
            kernel: [15]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        # Final 1024
        -   filters: 1024
            repeat: 1
            kernel: [1]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: false