model: "waveglow"
sample_rate: &sr 22050
n_fft: &n_fft 1024

AudioDataLayer_train:
    header: {full_spec: nemo.collections.tts.data_layers.AudioDataLayer,
        collection_type: tts, collection_version: null, nemo_core_version: 0.9.5}
    init_params:
        drop_last: false
        max_duration: null
        min_duration: 0.1
        n_segments: 16000
        sample_rate: *sr
        shuffle: true
        trim_silence: false
        # manifest_filepath: ljspeech_train.json  # Added by waveglow.py script
        # batch_size: 12
        # num_workers: 20

AudioDataLayer_eval:
    header: {full_spec: nemo.collections.tts.data_layers.AudioDataLayer,
        collection_type: tts, collection_version: null, nemo_core_version: 0.9.5}
    init_params:
        drop_last: false
        max_duration: null
        min_duration: 0.1
        n_segments: 0
        sample_rate: *sr
        shuffle: false
        trim_silence: false
        # manifest_filepath: ljspeech_eval.json  # Added by waveglow.py script
        # batch_size: 12
        # num_workers: 20


AudioToMelSpectrogramPreprocessor:
    header: {full_spec: nemo.collections.asr.audio_preprocessing.AudioToMelSpectrogramPreprocessor,
        collection_type: asr, collection_version: null, nemo_core_version: 0.9.5}
    init_params:
        dither: 0.0
        features: &n_mels 80
        frame_splicing: 1
        highfreq: 8000
        log: true
        log_zero_guard_type: clamp
        log_zero_guard_value: 1e-05
        lowfreq: 0
        mag_power: 1.0
        n_fft: *n_fft

        # Waveglow is currently hardcoded to these values for window size and stride
        # Changing these parameters are not recommended
        n_window_size: 1024
        n_window_stride: 256

        normalize: null
        pad_to: 16
        pad_value: -11.52
        preemph: null
        sample_rate: *sr
        stft_conv: true
        window: hann
        window_size: null
        window_stride: null

WaveGlowNM:
    header: {full_spec: nemo.collections.tts.waveglow_modules.WaveGlowNM,
        collection_type: tts, collection_version: null, nemo_core_version: 0.9.5}
    init_params:
        n_early_every: 4
        n_early_size: 2
        n_flows: 12
        n_group: 8
        n_mel_channels: *n_mels
        n_wn_channels: 512
        n_wn_layers: 8
        sample_rate: *sr
        wn_kernel_size: 3

WaveGlowLoss:
    header: {full_spec: nemo.collections.tts.waveglow_modules.WaveGlowLoss,
        collection_type: tts, collection_version: null, nemo_core_version: 0.9.5}
    init_params:
        sample_rate: *sr
        sigma: 1.0
