model: "waveglow"
sample_rate: &sr 22050
n_fft: &n_fft 1024

AudioDataLayer:
    sample_rate: *sr
    train:
        n_segments: 16000
        shuffle: true
    eval:
        shuffle: false

AudioToMelSpectrogramPreprocessor:
    normalize: null
    window_size: null
    window_stride: null
    # Waveglow is currently hardcoded to these values for window size and stride
    # Changing these parameters are not recommended
    n_window_size: 1024
    n_window_stride: 256
    window: "hann"
    features: &n_mels 80
    n_fft: *n_fft
    frame_splicing: 1
    dither: 0.
    # feat_type: "logfbank"
    stft_conv: true
    sample_rate: *sr
    highfreq: 8000
    preemph: null
    mag_power: 1.
    pad_value: -11.52
    log_zero_guard_type: "clamp"
    log_zero_guard_value: 1.0e-5

WaveGlowNM:
    n_mel_channels: *n_mels
    n_flows: 12
    n_group: 8
    n_early_every: 4
    n_early_size: 2
    n_wn_layers: 8
    n_wn_channels: 512
    wn_kernel_size: 3
