name: ia3_tuning_${model.new_tasks[0]}_max_epochs${trainer.max_epochs}

trainer:
  devices: 1
  accelerator: gpu
  num_nodes: 1
  precision: 16
  logger: False # logger provided by exp_manager
  enable_checkpointing: False
  use_distributed_sampler: False
  max_epochs: -1
  max_steps: 100 # consumed_samples = global_step * micro_batch_size * data_parallel_size * accumulate_grad_batches
  log_every_n_steps: 10
  val_check_interval: 0.2
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
  benchmark: False


exp_manager:
  explicit_log_dir: null
  exp_dir: null
  name: ${name}
  create_wandb_logger: null
  wandb_logger_kwargs:
    project: null
    name: null
  resume_from_checkpoint: null # The path to a checkpoint file to continue the training, restores the whole state including the epoch, step, LR schedulers, apex, etc.
  resume_if_exists: True
  resume_ignore_no_checkpoint: True
  create_checkpoint_callback: True
  checkpoint_callback_params:
    monitor: val_loss
    save_top_k: 1
    mode: min
    save_nemo_on_train_end: True # Should be false, correct prompt learning model file is saved at model.nemo_path set below, 
    filename: 'megatron_gpt_ia3_tuning--{val_loss:.3f}-{step}'
    model_parallel_size: ${model.tensor_model_parallel_size}
    save_best_model: True

model:
  seed: 1234
  nemo_path: ${exp_manager.exp_dir}/${name}.nemo # .nemo filename/absolute path to where the virtual prompt model parameters will be saved
  virtual_prompt_style: 'no-prompts' # adapter tuning requires no virtual prompts
  encoder_seq_length: 2048 
  gradient_as_bucket_view: false
  tensor_model_parallel_size: 1 # intra-layer model parallelism
  pipeline_model_parallel_size: 1 # inter-layer model parallelism
  global_batch_size: 8
  micro_batch_size: 4
  validation_global_batch_size: ${model.global_batch_size}
  validation_micro_batch_size: ${model.micro_batch_size}
  validation_drop_last: False

  restore_path: null # Path to an existing adapter .nemo model you wish to add new tasks to or run inference with
  language_model_path: ??? # Path to the GPT language model .nemo file, always required
  existing_tasks: [] # List of tasks the model has already been p-tuned/prompt-tuned for, needed when a restore path is given
  new_tasks: ["rte"] # List of new tasknames to be prompt-tuned

  task_templates: # Add more/replace tasks as needed, these are just examples
  - taskname: "boolq" # The task name
    prompt_template: "Passage: {passage} \nQuestion: {question} \nAnswer: {answer}" # Prompt template for task, specify virtual prompt positions with <|VIRTUAL_PROMPT_#|>
    total_virtual_tokens: 0 # Sum of tokens in virtual_token_splits must add to this number. Can differ between new and existing tasks, but must match across all new tasks being tuned at the same time.
    virtual_token_splits: [] # number of virtual tokens to be inserted at each VIRTUAL PROMPT location, must add to total_virtual_tokens
    truncate_field: "passage" # The {field} in the prompt template whose text will be truncated if the input is too long, if null, inputs that are too long will just be skipped.
    answer_only_loss: True 
    answer_field: "answer"

  - taskname: "intent_and_slot"
    prompt_template: "intent options: {intent_options} slot options: {slot_options} {utterance} \nintent: {intent} \nslot: {slot}"
    total_virtual_tokens: 0 
    answer_only_loss: True 
    virtual_token_splits: []
    truncate_field: null

  - taskname: "rte" 
    prompt_template: "sentence1: {premise} sentence2: {hypothesis} Answer: {answer}" 
    total_virtual_tokens: 0
    virtual_token_splits: []
    truncate_field: null
    answer_only_loss: True
    answer_field: "answer"

  - taskname: "squad" 
    prompt_template: "context: {context} question: {question} answer: {answer}" 
    total_virtual_tokens: 0
    virtual_token_splits: []
    truncate_field: null
    answer_only_loss: True
    answer_field: "answer"

  - taskname: "arc-challenge" 
    prompt_template: "question: {question} choices: {choices} answer: {answer}" 
    total_virtual_tokens: 0
    virtual_token_splits: []
    truncate_field: null
    answer_only_loss: True
    answer_field: "answer"

  - taskname: "xsum" 
    prompt_template: "{source} Summary: {target}" 
    total_virtual_tokens: 0
    virtual_token_splits: []
    truncate_field: null
    answer_only_loss: True
    answer_field: "target"

  data:
    train_ds: ??? # expects a list of paths to training data files
    validation_ds: ???  # expects a paths to validation data files
    add_eos: True
    shuffle: True
    num_workers: 8
    pin_memory: True


  optim:
    name: fused_adam
    lr: 1e-4
    weight_decay: 0.01 
    betas: 
    - 0.9
    - 0.98
    sched:
      name: CosineAnnealing
      warmup_steps: 50
      constant_steps: 0 # Constant steps should also be 0 when min_lr=0
      min_lr: 0.0 # min_lr must be 0.0 for prompt learning
      monitor: val_loss
      reduce_on_plateau: false
