name: megatron_audio_gpt_multi_enc_peft_tuning

trainer:
  devices: 1
  accelerator: gpu
  num_nodes: 1
  precision: 16
  logger: False # logger provided by exp_manager
  enable_checkpointing: False
  use_distributed_sampler: False
  max_epochs: 10000  # used to keep epoch logging correctly, but training will stop based on max_steps
  max_steps: 1000000 # 1M steps
  log_every_n_steps: 10 # frequency with which training steps are logged 
  val_check_interval: 3000 # If is an int n > 1, will run val every n training steps, if a float 0.0 - 1.0 will run val every epoch fraction, e.g. 0.25 will run val every quarter epoch
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1

exp_manager:
  # explicit_log_dir: null
  exp_dir: null
  name: ${name}
  create_wandb_logger: False
  wandb_logger_kwargs:
    project: null
    name: null
  resume_if_exists: True
  resume_ignore_no_checkpoint: True
  create_checkpoint_callback: True
  checkpoint_callback_params:
    monitor: validation_${model.data.validation_ds.metric.name}
    save_top_k: 1
    mode: min
    save_nemo_on_train_end: True
    filename: '${name}--{${exp_manager.checkpoint_callback_params.monitor}:.3f}-{step}-{epoch}'
    model_parallel_size: ${model.tensor_model_parallel_size}
    always_save_nemo: False
    save_best_model: True
  create_early_stopping_callback: False
  early_stopping_callback_params:
    monitor: "val_loss"
    mode: "min"
    min_delta: 0.001
    patience: 10
    verbose: True
    strict: False # Should be False to avoid a runtime error where EarlyStopping says monitor is unavailable, which sometimes happens with resumed training.


model:
  seed: 1234
  tensor_model_parallel_size: 1 # intra-layer model parallelism
  pipeline_model_parallel_size: 1 # inter-layer model parallelism
  
  freeze_llm: True
  freeze_audio_encoder: True
  freeze_modality_adapter: False

  global_batch_size: 128
  micro_batch_size: 4
  restore_from_path: ??? # Path to an existing .nemo model you wish to add new tasks to or run inference with
  resume_from_checkpoint: null # The path to a checkpoint file to continue the training, restores the whole state including the epoch, step, LR schedulers, apex, etc.
  save_nemo_on_validation_end: False # Saves an inference ready .nemo file every time a checkpoint is saved during training. 
  sync_batch_comm: False
  megatron_amp_O2: False

  ## Sequence Parallelism
  # Makes tensor parallelism more memory efficient for LLMs (20B+) by parallelizing layer norms and dropout sequentially
  # See Reducing Activation Recomputation in Large Transformer Models: https://arxiv.org/abs/2205.05198 for more details.
  sequence_parallel: False

  ## Activation Checkpoint 
  activations_checkpoint_granularity: null # 'selective' or 'full' 
  activations_checkpoint_method: null # 'uniform', 'block', not used with 'selective'
  # 'uniform' divides the total number of transformer layers and checkpoints the input activation
  # of each chunk at the specified granularity
  # 'block' checkpoints the specified number of layers per pipeline stage at the specified granularity
  activations_checkpoint_num_layers: null # not used with 'selective'
  activations_checkpoint_layers_per_pipeline: null
  answer_only_loss: True
  gradient_as_bucket_view: False

  hidden_dropout: 0.0
  attention_dropout: 0.0
  ffn_dropout: 0.0

  peft:
    peft_scheme: "lora"  # can be either adapter,ia3, or ptuning
    restore_from_path: null
    
    # Used for adapter peft training
    adapter_tuning:
      type: 'parallel_adapter' # this should be either 'parallel_adapter' or 'linear_adapter'
      adapter_dim: 32
      adapter_dropout: 0.0
      norm_position: 'pre' # This can be set to 'pre', 'post' or null, 'pre' is normally what is used.
      column_init_method: 'xavier' # IGNORED if linear_adapter is used, options: xavier, zero or normal
      row_init_method: 'zero' # IGNORED if linear_adapter is used, options: xavier, zero or normal
      norm_type: 'mixedfusedlayernorm' # IGNORED if layer_adapter is used,  options are ['layernorm', 'mixedfusedlayernorm']
      layer_selection: null  # selects in which layers to add adapters, e.g. [1,12] will add adapters to layer 1 (lowest) and 12. null will apply adapters to all layers
      weight_tying: False
      position_embedding_strategy: null # used only when weight_tying is True

    lora_tuning:
      target_modules: ['attention_qkv','attention_dense','mlp_fc1','mlp_fc2'] # this can either be 'attention_qkv','attention_dense','mlp_fc1','mlp_fc2', attention (qkv & dense), mlp (fc1 & fc2)
      adapter_dim: 32
      alpha: ${model.peft.lora_tuning.adapter_dim} 
      adapter_dropout: 0.0
      column_init_method: 'xavier' # IGNORED if linear_adapter is used, options: xavier, zero or normal
      row_init_method: 'zero' # IGNORED if linear_adapter is used, options: xavier, zero or normal
      layer_selection:  null  # selects in which layers to add lora adapters. e.g. [1,12] will add lora to layer 1 (lowest) and 12. null will apply adapters to all layers
      weight_tying: False
      position_embedding_strategy: null # used only when weight_tying is True

    # Used for p-tuning peft training
    p_tuning:
      virtual_tokens: 10  # The number of virtual tokens the prompt encoder should add at the start of the sequence
      bottleneck_dim: 1024  # the size of the prompt encoder mlp bottleneck
      embedding_dim: 1024  # the size of the prompt encoder embeddings
      init_std: 0.023

    ia3_tuning:
      layer_selection:  null  # selects in which layers to add ia3 adapters. e.g. [1,12] will add lora to layer 1 (lowest) and 12. null will apply adapters to all layers
    
    selective_tuning:
      tunable_base_param_names: ["self_attention", "word_embeddings"]  # TODO: regex support @adithyre


  perception:
    modality_adapter: 
      _target_: nemo.collections.multimodal.speech_llm.modules.PoolingMLPConnectors
      hidden_dim: 512
      pooling: 'cat'
      pooling_factor: 2
      num_layers: 4
      input_dim: -1
      output_dim: -1

    spec_augment:
      _target_: nemo.collections.asr.modules.SpectrogramAugmentation
      freq_masks: 2 # set to zero to disable it
      time_masks: 10 # set to zero to disable it
      freq_width: 27
      time_width: 0.05

    encoders:
    # use `target` instead of `_target_` to avoid auto initialization by hydra, need to do manual instantiation
      asr_model:
        target: nemo.collections.asr.models.EncDecRNNTBPEModel
        model_dim_key: d_model
        freeze: True
        pretrained_model: stt_en_fastconformer_transducer_large
      ssl_model:
        target: nemo.collections.asr.models.SpeechEncDecSelfSupervisedModel
        model_dim_key: d_model
        freeze: True
        pretrained_model: ssl_en_conformer_large
        use_multi_layer_feat: True
        multi_layer_feat:
          layer_idx_list: [0,16]
          aggregator:
            mode: "cat"
            pooling: "avg"
            rounding: "floor"
  
    speaker_model:
      segment_length_in_secs: 0.4
      freeze: True
      pretrained_model: titanet_large

    ref_model: asr_model
    aggregator:
      mode: "cat"
      pooling: "mean"
      rounding: "floor"

    # the following are read from the pretrained audio encoder:
    # output_dim: null
    # encoder: null
    # preprocessor: null

  data:
    end_string: "[EOG]"
    train_ds:
      # Example of how to specify paths to multiple datasets
      # manifest_filepath:
      #   - /path/to/squad.jsonl
      #   - /path/to/mnli.jsonl
      #   - /path/to/boolq.jsonl
      # Example of how each dataset is formatted
      # {'audio_filepath': 'audio1.wav', 'offset': 0.0, 'duration': 12.3, 'context': 'transcribe this audio', 'answer': 'I have a dream...'}
      # the 'answer' field can also be 'text', and a default 'context' field is added if missing in manigests, so as to work with ASR manifests
      manifest_filepath: ??? # Path to a list of JSONL files corresponding to the source data.
      global_batch_size: ${model.global_batch_size}
      micro_batch_size: ${model.micro_batch_size}
      shuffle: True
      num_workers: 0
      pin_memory: True
      max_seq_length: 2048
      min_seq_length: 1
      drop_last: True
      # Notably, the data weights are controlled by either bucketing_weights
      # or concat_sampling_probabilities depending on the dataset type (tar and
      # non-tar).
      # See audio_text_qa_dataset.py for details.
      concat_sampling_probabilities: null # When providing a list of datasets, this arg defines the sampling probabilities from each dataset when strategy='random'
      context_key: 'context'
      answer_key: 'answer'
      # add_eos: True
      add_eos: False
      end_string: ${model.data.end_string}
      add_sep: False
      add_bos: False
      separate_prompt_and_response_with_newline: False
      truncation_field: "context" # Options: ['context', 'answer']
      index_mapping_dir: null # Path to a directory to write index mapping files.
      prompt_template: "Q: {context}\nA: {answer}" # fstring to use for assistant prompt. Example: "Q: {input}\nA: {output}"
      # ASR configs
      sample_rate: 16000 #${model.audio_encoder.preprocessor.sample_rate}
      max_duration: 24 # it is set for LibriSpeech, you may need to update it for your dataset
      min_duration: 0.1
      # tarred datasets
      is_tarred: false
      tarred_audio_filepaths: null
      shuffle_n: 2048
      # bucketing params
      bucketing_strategy: "synced_randomized"
      bucketing_batch_size: null
      sample_alpha: null
      audio_locator: null

    validation_ds:
      manifest_filepath: ??? # Path to a list of JSONL files corresponding to the source data. Data format is identical to train_ds.
      global_batch_size: ${model.global_batch_size}
      micro_batch_size: ${model.micro_batch_size}
      shuffle: False
      num_workers: 0
      pin_memory: True
      max_seq_length: 2048
      min_seq_length: 1
      drop_last: False
      context_key: ${model.data.train_ds.context_key}
      answer_key: ${model.data.train_ds.answer_key}
      add_eos: ${model.data.train_ds.add_eos}
      end_string: ${model.data.end_string}
      add_sep: ${model.data.train_ds.add_sep}
      add_bos: ${model.data.train_ds.add_bos}
      separate_prompt_and_response_with_newline: ${model.data.train_ds.separate_prompt_and_response_with_newline}
      write_predictions_to_file: False
      output_file_path_prefix: null # Prefix of the file to write predictions to.
      truncation_field: "context" # Options: ['context', 'answer']
      index_mapping_dir: null # Path to a directory to write index mapping files.
      prompt_template: ${model.data.train_ds.prompt_template} # fstring to use for assistant prompt. Example: "Q: {input}\nA: {output}"
      tokens_to_generate: 128
      # ASR configs
      sample_rate: 16000 #${model.audio_encoder.preprocessor.sample_rate}
      audio_locator: ${model.data.train_ds.audio_locator}

      log_every_n_steps: 20
      metric:
        name: "wer" # Name of the evaluation metric to use. Options: ['exact_string_match', 'loss']
        average: null # Average the metric over the dataset. Options: ['macro', 'micro']. Works only for 'F1', 'accuracy' etc. Refer to torchmetrics for metrics where this is supported.
        num_classes: null

    # test_ds:
    #   manifest_filepath: null # Path to a list of JSONL files corresponding to the source data. Data format is identical to train_ds.
    #   names: null # Names of the corresponding datasets used to log metrics.
    #   global_batch_size: ${model.global_batch_size}
    #   micro_batch_size: ${model.micro_batch_size}
    #   shuffle: False
    #   num_workers: 4
    #   pin_memory: True
    #   max_seq_length: 2048
    #   min_seq_length: 1
    #   drop_last: False
    #   context_key: 'context'
    #   answer_key: 'answer'
    #   add_eos: ${model.data.train_ds.add_eos}
    #  end_string: ${model.data.end_string}
    #   add_sep: ${model.data.train_ds.add_sep}
    #   add_bos: ${model.data.train_ds.add_bos}
    #   separate_prompt_and_response_with_newline: ${model.data.train_ds.separate_prompt_and_response_with_newline}
    #   write_predictions_to_file: False
    #   output_file_path_prefix: null # Prefix of the file to write predictions to.
    #   truncation_field: "context" # Options: ['context', 'answer']
    #   index_mapping_dir: null # Path to a directory to write index mapping files.
    #   prompt_template: ${model.data.train_ds.prompt_template}
    #   # ASR configs
    #   sample_rate: 16000 #${model.audio_encoder.preprocessor.sample_rate}

    #   metric:
    #     name: "loss" # Name of the evaluation metric to use. Options: ['exact_string_match', 'loss']
    #     average: null # Average the metric over the dataset. Options: ['macro', 'micro']. Works only for 'F1', 'accuracy' etc. Refer to torchmetrics for metrics where this is supported.
    #     num_classes: null

  optim:
    name: fused_adam
    lr: 1e-4
    weight_decay: 0.001 
    betas: 
    - 0.9
    - 0.98
    sched:
      name: CosineAnnealing
      warmup_steps: 5000
      min_lr: 0.0 # min_lr must be 0.0 for prompt learning when pipeline parallel > 1
      constant_steps: 0 # Constant steps should also be 0 when min_lr=0
      monitor: val_loss
      reduce_on_plateau: false
