model: "Jasper"
sample_rate: 16000
dropout: &drop 0.0
repeat:  &rep  1

AudioToTextDataLayer:
    train:
        shuffle: true
    eval:
        shuffle: false

AudioToMelSpectrogramPreprocessor:
    normalize: "per_feature"
    window_size: 0.02
    window_stride: 0.01
    window: "hann"
    features: 64
    n_fft: 512
    frame_splicing: 1
    dither: 0.00001
    stft_conv: true

JasperEncoder:
    activation: "relu"

    jasper:
        - filters: 128
          repeat: 1
          kernel: [11]
          stride: [1]
          dilation: [1]
          dropout: *drop
          residual: true

        - filters: 256
          repeat: *rep
          kernel: [13]
          stride: [1]
          dilation: [1]
          dropout: *drop
          residual: true

        - filters: 256
          repeat: *rep
          kernel: [15]
          stride: [1]
          dilation: [1]
          dropout: *drop
          residual: true

        - filters: 256
          repeat: *rep
          kernel: [17]
          stride: [1]
          dilation: [1]
          dropout: *drop
          residual: true

        - filters: 256
          repeat: *rep
          kernel: [19]
          stride: [1]
          dilation: [1]
          dropout: *drop
          residual: true

        - filters: 256
          repeat: 1
          kernel: [21]
          stride: [1]
          dilation: [1]
          dropout: 0.0
          residual: false

        - filters: 1024
          repeat: 1
          kernel: [1]
          stride: [1]
          dilation: [1]
          dropout: 0.0
          residual: false

labels: [" ", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m",
         "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "'"]
