model: "QuartzNet"
sample_rate: &sample_rate 16000
dropout: &drop 0.0
repeat:  &rep  1
augment: true
lr_schedule: "PolynomialHoldDecayAnnealing"
lr_warmup_proportion: 0.1
kernel_size_factor: &kfactor 1.0

AudioToSpeechLabelDataLayer:
    #sample_rate: *sample_rate
    train:
        shuffle: true
    eval:
        shuffle: false

AudioToMelSpectrogramPreprocessor:
    normalize: "per_feature"
    window_size: 0.025
    window_stride: 0.01
    window: "hann"
    features: &n_mels 64
    frame_splicing: 1
    dither: 0.00001
    stft_conv: true
    n_fft: 512

AudioToMFCCPreprocessor:
    window_size: 0.025
    window_stride: 0.01
    window: "hann"
    n_mels: *n_mels
    n_mfcc: *n_mels
    n_fft: 512

AudioAugmentor:
    shift:
        prob: 1.0
        min_shift_ms: -5.0
        max_shift_ms: 5.0
    white_noise:
        prob: 1.0
        min_level: -90
        max_level: -46

SpectrogramAugmentation:
    freq_masks: 2
    time_masks: 2
    freq_width: 15
    time_width: 25
    rect_masks: 5
    rect_time: 25
    rect_freq: 15

JasperEncoder:
    feat_in: *n_mels
    activation: "relu"
    conv_mask: true

    jasper:
        - filters: 128
          repeat: 1
          kernel: [11]
          stride: [1]
          dilation: [1]
          dropout: *drop
          residual: false
          separable: true
          kernel_size_factor: *kfactor

        - filters: 64
          repeat: *rep
          kernel: [13]
          stride: [1]
          dilation: [1]
          dropout: *drop
          residual: true
          separable: true
          kernel_size_factor: *kfactor

        - filters: 64
          repeat: *rep
          kernel: [15]
          stride: [1]
          dilation: [1]
          dropout: *drop
          residual: true
          separable: true
          kernel_size_factor: *kfactor

        - filters: 64
          repeat: *rep
          kernel: [17]
          stride: [1]
          dilation: [1]
          dropout: *drop
          residual: true
          separable: true
          kernel_size_factor: *kfactor

        - filters: 128
          repeat: 1
          kernel: [29]
          stride: [1]
          dilation: [2]
          dropout: *drop
          residual: false
          separable: true
          kernel_size_factor: *kfactor

        - filters: 128
          repeat: 1
          kernel: [1]
          stride: [1]
          dilation: [1]
          dropout: *drop
          residual: false

JasperDecoderForClassification:
    return_logits: True
    pooling_type: 'avg'

labels: ['visual', 'wow', 'learn', 'backward', 'dog', 'two', 'left', 'happy', 'nine', 'go', 'up', 'bed', 'stop', 'one', 'zero', 'tree', 'seven', 'on', 'four', 'bird', 'right', 'eight', 'no', 'six', 'forward', 'house', 'marvin', 'sheila', 'five', 'off', 'three', 'down', 'cat', 'follow', 'yes']