defaults:
  - _self_
  - cluster: bcm
  - search_config: gpt3/5b
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null

run_training_hp_search: True
run_inference_hp_search: True

bignlp_hp_tool_path: ???  # Path to the location of bignlp-hp-tool codebase.
bignlp_scripts_path: ${bignlp_hp_tool_path}/../bignlp-scripts  # Path to the location of BigNLP-Inference-Scripts codebase.
data_dir: ${bignlp_scripts_path}/data
base_results_dir: ${bignlp_hp_tool_path}/results

training_container: nvcr.io/ea-bignlp/bignlp-training:22.05-py3
inference_container: nvcr.io/ea-bignlp/bignlp-inference:22.05-py3
container_mounts:
    - null

wandb:  # Weights and Biases (W&B) logging.
  enable: False  # Whether to save logs to W&B.
  api_key_file: null  # Path to the file where the w&B api key is stored. Key must be on the first line.
  project: bignlp-hp-tool  # Name of the W&B project to store the logs in. The name of the run will be populated automatically.

# Do not modify the code below.
search_config_value: ${hydra:runtime.choices.search_config}
