
# Question Answering with SQUAD

pl:
  trainer:
    gpus: 1 # the number of gpus, 0 for CPU, or list with gpu indices
    num_nodes: 1
    max_epochs: 10 # the number of training epochs
    max_steps: null # precedence over max_epochs
    accumulate_grad_batches: 1 # accumulates grads every k batches
    precision: 32 # 16 to use AMP
    amp_level: O1 # O1 or O2 if using AMP 
    distributed_backend: ddp
    gradient_clip_val: 1.0
    val_check_interval: 1.0 # check once per epoch .25 for 4 times per epoch

model:
  max_answer_length: 30
  # The maximum length of an answer that can be 
  # generated. This is needed because the start
  # and end predictions are not conditioned
  # on one another.

  output_prediction_file: predictions.json
  # File to write predictions to. Only in evaluation or test mode,
      
  output_nbest_file: nbest.json
  # File to write nbest predictions to. Only in evaluation or test mode.

  version_2_with_negative: false
  # If true, the examples contain some that do not have an answer.

  null_score_diff_threshold: 0.0
  # If null_score - best_non_null is greater than the threshold predict null.

  n_best_size: 20
  # The total number of n-best predictions to generate at testing.

  mode: train_eval
  # Choices: train, train_eval, eval, test
  # Mode of model usage.
  # When using test mode the script is running inference on the data,
  # i.e. no ground-truth labels are required in the dataset.

  doc_stride: 128
  # When splitting up a long document into chunks,
  # how much stride to take between chunks.

  max_query_length: 64
  # The maximum number of tokens for the question.
  # Questions longer than this will be truncated to
  # this length.

  max_seq_length: 384
  # The maximum total input sequence length after
  # WordPiece tokenization. Sequences longer than this
  # will be truncated, and sequences shorter than this
  # will be padded.

  train_ds:
    mode: train
    file: null # .json file
    batch_size: 8 # per GPU
    shuffle: true
    num_samples: -1
    num_workers: 2
    use_cache: true
    drop_last: false
    pin_memory: false

  validation_ds:
    mode: eval
    file: null # .json file
    batch_size: 8 # per GPU
    shuffle: false
    num_samples: -1
    num_workers: 2
    use_cache: true
    drop_last: false
    pin_memory: false
  
  optim:
    name: adam
    lr: 2e-5
    args:
      name: auto
      params:
        weight_decay: 0.01

    sched:
      name: CosineAnnealing
      iters_per_batch: null # computed at runtime
      max_steps: null # computed at runtime or explicitly set here

      # pytorch lightning args
      monitor: val_loss
      reduce_on_plateau: false

      # scheduler config override
      args:
        name: auto
        params:
          warmup_steps: null
          warmup_ratio: 0.1
          last_epoch: -1


  language_model:
    pretrained_model_name: bert-base-uncased
    max_seq_length: 384
    bert_checkpoint: null
    bert_config: null
    tokenizer: null # only used if using custom checkpoint
    tokenizer_model: null # only used if tokenizer is sentencepiece
    do_lower_case: true # true for uncased models, false for cased models
  
  token_classifier:
    num_layers: 2
    dropout: 0.1
    num_classes: 2
    activation: relu
    log_softmax: false
    use_transformer_init: true

  pl: null # used at runtime