# Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.
# Copyright 2018 The Google AI Language Team Authors and
# The HuggingFace Inc. team.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Config file for text classification with pretrained BERT models

trainer:
  gpus: 1 # the number of gpus, 0 for CPU
  num_nodes: 1
  max_epochs: 300
  max_steps: null # precedence over max_epochs
  accumulate_grad_batches: 1 # accumulates grads every k batches
  gradient_clip_val: 0.0
  amp_level: O0 # O1/O2 for mixed precision
  precision: 16 # Should be set to 16 for O1 and O2, default is 16 as PT ignores it when am_level is O0
  distributed_backend: ddp
  row_log_interval: 1  # Interval of logging.
  val_check_interval: 1.0  # Set to 0.25 to check 4 times per epoch, or an int for number of iterations
  resume_from_checkpoint: null # The path to a checkpoint file to continue the training, restores the whole state including the epoch, step, LR schedulers, apex, etc.

  checkpoint_callback: False  # Provided by exp_manager
  logger: False  # Provided by exp_manager

model:
  dataset:
    do_lower_case: false # true for uncased models, false for cased models, will be set automatically if pre-trained tokenizer model is used
    max_seq_length: 36
    class_balancing: null # null or weighted_loss

    # parameters shared among all data loaders
    use_cache: false # uses a cache to store the processed dataset, you may use it for large datasets for speed up
    num_workers: 2 # number of workers for data loaders
    drop_last: false # drops the last last batch if it is smaller than the batch size
    pin_memory: false # enables pin_memory feature of the data loaders

  train_ds:
    file_name: ???
    batch_size: 32
    shuffle: true
    num_samples: -1 # number of samples to be considered, -1 means all the dataset

  validation_ds:
    file_name: null
    batch_size: 32
    shuffle: false
    num_samples: -1 # number of samples to be considered, -1 means all the dataset

  language_model:
    pretrained_model_name: roberta-base
    tokenizer: nemobert # 'nemobert' or 'sentencepiece'
    bert_checkpoint_file: null # the path of a checkpoint file of a BERT-like model if a customized checkpoint is supposed to be used
    bert_config: null
    vocab_file: null
    tokenizer_model: null # only used if tokenizer is sentencepiece

  head:
    num_output_layers: 2
    fc_dropout: 0.1

  optim:
    name: adam
    lr: 2e-5
    # optimizer arguments
    betas: [0.9, 0.999]
    weight_decay: 0.01

    # scheduler setup
    sched:
      name: WarmupAnnealing
      # Scheduler params
      warmup_steps: null
      warmup_ratio: 0.1
      last_epoch: -1

      # pytorch lightning args
      monitor: val_loss
      reduce_on_plateau: false

exp_manager:
  exp_dir: null  # exp_dir for your experiment, if None, defaults to "./nemo_experiments"
  name: "TextClassification"  # The name of your model
  create_tensorboard_logger: True  # Whether you want exp_manger to create a tb logger
  create_checkpoint_callback: True  # Whether you want exp_manager to create a modelcheckpoint callback

hydra:
  run:
    dir: .
  job_logging:
    root:
      handlers: null
