name: megatron_t5_glue_eval

trainer:
  devices: 1
  num_nodes: 1
  accelerator: gpu
  strategy: ddp
  precision: 16
  logger: False # logger provided by exp_manager
  enable_checkpointing: False
  replace_sampler_ddp: False
  log_every_n_steps: 10


exp_manager:
  explicit_log_dir: null
  exp_dir: null
  name: megatron_t5_glue_eval
  enable_checkpointing: False  # Provided by exp_manager

model:
  restore_from_finetuned_path: ??? # Path to a finetuned T5 .nemo file
  tensor_model_parallel_size: 1
  gradient_as_bucket_view: True # Allocate gradients in a contiguous bucket to save memory (less fragmentation and buffer memory)
  megatron_amp_O2: False # Enable O2 optimization for megatron amp

  data:
    validation_ds:
      task_name: 'mnli'
      file_path: ??? # Path to the TSV file for MNLI dev ex: '/raid/Data/GLUE/MNLI/dev_matched.tsv'
      batch_size: 32
      shuffle: False
      num_workers: 4
      pin_memory: True
      max_seq_length: 512
