# Copyright (c) 2020-2021, NVIDIA CORPORATION.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build, test, and publish a PyPi wheel (to testpypi)

on: 
  push:
    branches:
      - main
      - 'r**'

defaults:
  run:
    shell: bash -x -e -u -o pipefail {0}

jobs:
  build-test-publish-wheel:
    uses: NVIDIA/NeMo-FW-CI-templates/.github/workflows/_build_test_publish_wheel.yml@v0.5.0
    with:
      image-name: nemo_container
      dockerfile: Dockerfile.ci
      image-label: nemo-core
      build-args: |
        IMAGE_LABEL=nemo-core
      prune-filter-timerange: 24h
      dry-run: true
      python-package: nemo
      container-workdir: /workspace
      environment: public
    secrets:
      TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}

  notify:
    runs-on: ubuntu-latest
    if: failure()
    needs: [build-test-publish-wheel]
    env:
      RUN_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
      SLACK_WEBHOOK_ADMIN: "<!subteam^${{ secrets.SLACK_WEBHOOK_ADMIN }}>"
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      COMMIT_URL: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
      COMMIT_SHA: ${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: NVIDIA/NeMo-FW-CI-templates
          ref: v0.5.0
          path: send-slack-alert

      - name: Send Slack alert
        uses: ./send-slack-alert/.github/actions/send-slack-alert
        with:
          message: >
            <${{ env.RUN_URL }}|Build, test, and push PyPi wheel (test)> has failed for <${{ env.COMMIT_URL }}|${{ env.COMMIT_SHA }}>.

            cc: ${{ env.SLACK_WEBHOOK_ADMIN }}
          webhook: ${{ env.SLACK_WEBHOOK }}