name: Create PR to main with cherry-pick from release

on: 
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    environment: 
      name: main
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}


      - name: Cherry pick
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          set -x  
          set +e

          git config --global user.email "nemo-bot@nvidia.com"
          git config --global user.name "NeMo Bot"
          
          SHA=$(git rev-list --no-merges -n 1 HEAD)
          MESSAGE=$(git log -n 1 --pretty=format:%s $SHA)
          PR_ID=$(echo $MESSAGE | awk -F'#' '{print $2}' | awk -F')' '{print $1}' )
          USERNAME=$(git log -n 1 --pretty=format:%ae $SHA | awk -F'@' '{print $1}')

          PR=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/NVIDIA/NeMo/pulls/$PR_ID)
          PR_TITLE=$(echo -E $PR | jq '.title' | tr -d '"')
          
          LABELS=$(echo -E $PR | jq '.labels | [.[].name] | join(",")' | tr -d '"')
          AUTHOR=$(echo -E $PR | jq '.user.login' | tr -d '"')

          TARGET_BRANCHES=$(echo "$LABELS" | grep -o 'r[^,]*')
      
          if [[ $TARGET_BRANCHES == '' ]]; then
            echo Nothing to cherry-pick
            exit 0
          fi

          echo $TARGET_BRANCHES | while read -r RELEASE_BRANCH ; do
            TARGET_BRANCH_EXISTS_OK=$([[ "$(git ls-remote --heads origin refs/heads/$RELEASE_BRANCH)" != "" ]] && echo true || echo false)
          
            if [[ "$TARGET_BRANCH_EXISTS_OK" == "false" ]]; then
              echo Release branch does not yet exist, will not  cherry-pick
              continue
            fi
            
            (
              git fetch origin $RELEASE_BRANCH:$RELEASE_BRANCH
              git switch --force-create cherry-pick-$PR_ID-$RELEASE_BRANCH $RELEASE_BRANCH
              git cherry-pick $SHA
              git push -u origin --force cherry-pick-$PR_ID-$RELEASE_BRANCH
              git checkout ${CI_DEFAULT_BRANCH:-main}
            )

            CHERRYPICK_SUCCESSFUL=$?

            if [[ $CHERRYPICK_SUCCESSFUL -eq 0 ]]; then
              PR_URL="https://github.com/NVIDIA/NeMo/pull/$PR_ID"

              PAYLOAD=$(jq \
                -n \
                -c \
                --arg TITLE "Cherry pick \`$PR_TITLE ($PR_ID)\` into \`$RELEASE_BRANCH\`" \
                --arg HEAD "cherry-pick-$PR_ID-$RELEASE_BRANCH" \
                --arg RELEASE_BRANCH "$RELEASE_BRANCH" \
                --arg BODY "[ðŸ¤–]: Hi @$AUTHOR ðŸ‘‹,<br><br>we've cherry picked #$PR_ID into \`$RELEASE_BRANCH\` for you! ðŸš€<br><br>Please review and approve this cherry pick by your convenience\!" \
                '{
                  "title": $TITLE,
                  "head": $HEAD,
                  "base": $RELEASE_BRANCH,
                  "body": $BODY
                }'
              )

              NEW_PR=$(curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer $GH_TOKEN" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/NVIDIA/NeMo/pulls \
                -d "$PAYLOAD")
                
              NEW_PR_ID=$(echo -E $NEW_PR | jq '.number')
              curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer $GH_TOKEN" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/NVIDIA/NeMo/pulls/$NEW_PR_ID/requested_reviewers \
                -d '{"reviewers":["'$AUTHOR'"]}'
              
              curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer $GH_TOKEN" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/NVIDIA/NeMo/issues/$NEW_PR_ID/labels \
                -d '{"labels":["Run CICD", "cherry-pick"]}'

            else
              URL="https://github.com/NVIDIA/NeMo/pull/$PR_ID"

              MESSAGE='{
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": ":alert: Cherrypick bot ðŸ¤–: Hey <@'$USERNAME'>: Cherry-pick of <'$URL'|#'$PR_ID'> failed (3-way merge impossible). Please resolve manually and create a PR.\n\ncc: <!subteam^{{ secrets.SLACK_WEBHOOK_ADMIN }}>"
                    }
                  }
                ]
              }'

              curl -X POST -H "Content-type: application/json" --data "$MESSAGE" ${{ secrets.SLACK_WEBHOOK }}

            fi

          done
   
          

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}