name: Create PR to main with cherry-pick from release

on: 
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    environment: 
      name: main
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}


      - name: Cherry pick
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          set -x  
          set +e

          git config --global user.email "nemo-bot@nvidia.com"
          git config --global user.name "NeMo Bot"
          
          SHA=$(git rev-list --no-merges -n 1 HEAD)
          MESSAGE=$(git log -n 1 --pretty=format:%s $SHA)
          PR_ID=$(echo $MESSAGE | awk -F'#' '{print $2}' | awk -F')' '{print $1}' )

          PR=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/NVIDIA/NeMo/pulls/$PR_ID)
          
          LABELS=$(echo -E $PR | jq '.labels | [.[].name] | join(",")' | tr -d '"')

          TARGET_BRANCHES=$(echo "$LABELS" | grep -o 'r[^,]*')
      
          if [[ $TARGET_BRANCHES == '' ]]; then
            echo Nothing to cherry-pick
            exit 0
          fi

          echo $TARGET_BRANCHES | while read -r RELEASE_BRANCH ; do
            TARGET_BRANCH_EXISTS_OK=$([[ "$(git ls-remote --heads origin refs/heads/$RELEASE_BRANCH)" != "" ]] && echo true || echo false)
          
            if [[ "$TARGET_BRANCH_EXISTS_OK" == "false" ]]; then
              echo Release branch does not yet exist, will not  cherry-pick
              continue
            fi
            
            (
              git fetch origin $RELEASE_BRANCH:$RELEASE_BRANCH
              git switch --force-create cherry-pick-$PR_ID-$RELEASE_BRANCH $RELEASE_BRANCH
              git cherry-pick $SHA
              git push -u origin --force cherry-pick-$PR_ID-$RELEASE_BRANCH
              git checkout ${CI_DEFAULT_BRANCH:-main}
            )

            CHERRYPICK_SUCCESSFUL=$?

            if [[ $CHERRYPICK_SUCCESSFUL -eq 0 ]]; then
              curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer $GH_TOKEN" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/NVIDIA/NeMo/pulls \
                -d '{"title":"Cherry-pick '$PR_ID' into '$RELEASE_BRANCH'","head":"cherry-pick-'$PR_ID'-'$RELEASE_BRANCH'","base":"'$RELEASE_BRANCH'"}'

            else
              URL=https://github.com/NVIDIA/NeMo/pull/${{ github.event.number }}

              MESSAGE='{
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": ":alert: Cherrypick bot ðŸ¤–: Cherry-pick of <'$URL'|#'${{ github.event.number }}'> failed"
                    }
                  }
                ]
              }'

              curl -X POST -H "Content-type: application/json" --data "$MESSAGE" ${{ secrets.SLACK_WEBHOOK }}

            fi

          done
   
          

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}