name: NeMo Unit Tests
on:
  workflow_call:
    inputs:
      test_to_run:
        required: true
        type: string

jobs:
  collections-asr-tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - script: L0_Unit_Tests_GPU_ASR
            runner: self-hosted-azure-gpus-1
          - script: L0_Unit_Tests_CPU_ASR
            runner: self-hosted-azure-cpu
    uses: ./.github/workflows/_test_template.yml
    with:
      RUNNER: ${{ matrix.runner }}
      SCRIPT: ${{ matrix.script }}
      TIMEOUT: 20
      IS_UNIT_TEST: true
      TESTS_TO_RUN: ${{ inputs.test_to_run }}

  collections-audio-tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - script: L0_Unit_Tests_GPU_Audio
            runner: self-hosted-azure-gpus-1
          - script: L0_Unit_Tests_CPU_Audio
            runner: self-hosted-azure-cpu
    uses: ./.github/workflows/_test_template.yml
    with:
      RUNNER: ${{ matrix.runner }}
      SCRIPT: ${{ matrix.script }}
      TIMEOUT: 20
      IS_UNIT_TEST: true
      TESTS_TO_RUN: ${{ inputs.test_to_run }}

  collections-common-tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - script: L0_Unit_Tests_GPU_Common
            runner: self-hosted-azure-gpus-1
          - script: L0_Unit_Tests_CPU_Common
            runner: self-hosted-azure-cpu
    uses: ./.github/workflows/_test_template.yml
    with:
      RUNNER: ${{ matrix.runner }}
      SCRIPT: ${{ matrix.script }}
      TIMEOUT: 20
      IS_UNIT_TEST: true
      TESTS_TO_RUN: ${{ inputs.test_to_run }}

  collections-llm-tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - script: L0_Unit_Tests_GPU_LLM
            runner: self-hosted-azure-gpus-1
          - script: L0_Unit_Tests_CPU_LLM
            runner: self-hosted-azure-cpu
    uses: ./.github/workflows/_test_template.yml
    with:
      RUNNER: ${{ matrix.runner }}
      SCRIPT: ${{ matrix.script }}
      IS_UNIT_TEST: true
      TESTS_TO_RUN: ${{ inputs.test_to_run }}

  collections-multimodal-tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - script: L0_Unit_Tests_GPU_Multimodal
            runner: self-hosted-azure-gpus-1
          - script: L0_Unit_Tests_CPU_Multimodal
            runner: self-hosted-azure-cpu
    uses: ./.github/workflows/_test_template.yml
    with:
      RUNNER: ${{ matrix.runner }}
      SCRIPT: ${{ matrix.script }}
      IS_UNIT_TEST: true
      TESTS_TO_RUN: ${{ inputs.test_to_run }}

  collections-tts-tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - script: L0_Unit_Tests_GPU_TTS
            runner: self-hosted-azure-gpus-1
          - script: L0_Unit_Tests_CPU_TTS
            runner: self-hosted-azure-cpu
    uses: ./.github/workflows/_test_template.yml
    with:
      RUNNER: ${{ matrix.runner }}
      SCRIPT: ${{ matrix.script }}
      IS_UNIT_TEST: true
      TESTS_TO_RUN: ${{ inputs.test_to_run }}

  collections-vlm-tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - script: L0_Unit_Tests_GPU_VLM
            runner: self-hosted-azure-gpus-1
          - script: L0_Unit_Tests_CPU_VLM
            runner: self-hosted-azure-cpu
    uses: ./.github/workflows/_test_template.yml
    with:
      RUNNER: ${{ matrix.runner }}
      SCRIPT: ${{ matrix.script }}
      IS_UNIT_TEST: true
      TESTS_TO_RUN: ${{ inputs.test_to_run }}

  core-tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - script: L0_Unit_Tests_GPU_Core
            runner: self-hosted-azure-gpus-1
          - script: L0_Unit_Tests_CPU_Core
            runner: self-hosted-azure-cpu
          - script: L0_Unit_Tests_GPU_Hydra
            runner: self-hosted-azure-gpus-1
          - script: L0_Unit_Tests_CPU_Hydra
            runner: self-hosted-azure-cpu
    uses: ./.github/workflows/_test_template.yml
    with:
      RUNNER: ${{ matrix.runner }}
      SCRIPT: ${{ matrix.script }}
      IS_UNIT_TEST: true
      TESTS_TO_RUN: ${{ inputs.test_to_run }}

  lightning-tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - script: L0_Unit_Tests_GPU_Lightning
            runner: self-hosted-azure
          - script: L0_Unit_Tests_CPU_Lightning
            runner: self-hosted-azure-cpu
    uses: ./.github/workflows/_test_template.yml
    with:
      RUNNER: ${{ matrix.runner }}
      SCRIPT: ${{ matrix.script }}
      IS_UNIT_TEST: true
      TESTS_TO_RUN: ${{ inputs.test_to_run }}

  other-tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - script: L0_Unit_Tests_GPU_Others
            runner: self-hosted-azure-gpus-1
          - script: L0_Unit_Tests_CPU_Others
            runner: self-hosted-azure-cpu
    uses: ./.github/workflows/_test_template.yml
    with:
      RUNNER: ${{ matrix.runner }}
      SCRIPT: ${{ matrix.script }}
      IS_UNIT_TEST: true
      TESTS_TO_RUN: ${{ inputs.test_to_run }}
