name: NeMo E2E Export Deploy Tests
on:
  workflow_call:
    inputs:
      test_to_run:
        required: true
        type: string
      image-name:
        required: false
        default: nemo_container_export_deploy
        type: string

jobs:
  export-deploy-build:
    uses: ./.github/workflows/_build_container.yml
    with:
      image-name: ${{ inputs.image-name }}
      dockerfile: Dockerfile.ci.export_deploy

  export-deploy-unit-tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - script: L0_Unit_Tests_GPU_Export_Deploy
            runner: self-hosted-azure
          - script: L0_Unit_Tests_CPU_Export_Deploy
            runner: self-hosted-azure-cpu
          - script: L0_Unit_Tests_Eval
            runner: self-hosted-azure
    uses: ./.github/workflows/_test_template.yml
    needs: [export-deploy-build]
    with:
      RUNNER: ${{ matrix.runner }}
      SCRIPT: ${{ matrix.script }}
      IS_UNIT_TEST: true
      TESTS_TO_RUN: ${{ inputs.test_to_run }}

  e2e-tests-export-deploy-tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Export tests
          - script: L2_NeMo_2_Export_HF_TRT_LLM
            runner: self-hosted-azure
          - script: L2_NeMo_2_Export_Deploy_Query_In_Framework
            runner: self-hosted-azure
          - script: L2_ONNX_TRT_LLM_Embedding_Export
            runner: self-hosted-azure
          - script: L2_NeMo_2_Export_TRT_LLM
            runner: self-hosted-azure
          - script: L2_NeMo_2_VLLM_EXPORT
            runner: self-hosted-azure
          - script: L2_NeMo_2_Export_In_Framework
            runner: self-hosted-azure
          - script: L2_NeMo_2_VLLM_VISION
            runner: self-hosted-azure
    uses: ./.github/workflows/_test_template.yml
    needs: [export-deploy-unit-tests]
    with:
      RUNNER: ${{ matrix.runner }}
      SCRIPT: ${{ matrix.script }}
      TESTS_TO_RUN: ${{ inputs.test_to_run }}
      IMAGE: ${{ inputs.image-name }}
