name: CI-Install-Check

on:
  pull_request:
    paths:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-installs-macos:
    name: ${{ matrix.os }}-py${{ matrix.python }}-${{ matrix.installer }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        python: ["3.10", "3.11", "3.12"]
        installer: ["pip-install", "nemo-install"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python }}"

      - name: Install NeMo
        env:
          INSTALLER: ${{ matrix.installer }}
          NEMO_TAG: ${{ github.sha }}
          NEMO_REPO: ${{ github.server_url }}/${{ github.repository }}
        run: |
          if [[ "$INSTALLER" == "pip-install" ]]; then
            pip install ".[all]"
          else
            export NEMO_TAG
            export NEMO_REPO
            export INSTALL_DIR=$(pwd)
            
            bash reinstall.sh --library all --mode install
          fi

      - name: Run LLM example
        if: ${{ matrix.installer == 'nemo-install' }}
        run: |
          # This is guarded since it requires nemo-run. We expect Nemo-run to be
          # available on PyPi with 25.04.

          pip install jupyter nbconvert
          jupyter nbconvert --to script examples/llm/pretrain/pretrain.ipynb
          python examples/llm/pretrain/pretrain.py

      - name: Run import checks
        run: |
          # Run import checks
          for collection in "asr" "tts"; do
            python tests/core_ptl/check_imports.py --domain "$collection"
          done

  test-installs-linux:
    name: ${{ matrix.os }}-${{ matrix.image }}-${{ matrix.installer }}
    runs-on: ubuntu-latest
    container: ubuntu:${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        image: ["22.04"]
        installer: ["pip-install", "nemo-install"]
    env:
      collections: '("asr" "tts", "nlp")'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Python
        run: |
          apt-get update && apt-get install -y python3-pip jq git python-is-python3

      - name: Install NeMo
        env:
          INSTALLER: ${{ matrix.installer }}
        run: |
          if [ "$INSTALLER" = "pip-install" ]; then
            pip install --upgrade pip
            pip install ".[all]"
          else
            export INSTALL_DIR=$(pwd)
            bash reinstall.sh --library all --mode install
          fi

      - name: Run LLM example
        if: ${{ matrix.installer == 'nemo-install' }}
        run: |
          # This is guarded since it requires nemo-run. We expect Nemo-run to be
          # available on PyPi with 25.04.

          pip install jupyter nbconvert
          jupyter nbconvert --to script examples/llm/pretrain/pretrain.ipynb
          python examples/llm/pretrain/pretrain.py

      - name: Run import checks
        run: |
          # Run import checks
          for collection in "asr" "tts"; do
            python tests/core_ptl/check_imports.py --domain "$collection"
          done
